name: Test Vno Frontend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: ['v1.10.2']

    steps:
      - name: Git Checkout Deno Mod
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: ${{ matrix.deno-version }}
